---
name: Ansible-test
'on':
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      ansible_version:
        required: true
        type: string
jobs:
  sanity:
    name: Run ansible-test sanity tests
    runs-on:
      - self-hosted
      - linux
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.working_directory }}
      - name: Run Molecule tests
        working-directory: '${{ inputs.working_directory }}'
        run: |
          source ~/venv/ansible-test-${{ inputs.ansible_version }}/bin/activate
          ansible-test sanity -v --docker
          deactivate
