---
name: Molecule
'on':
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      role_name:
        required: true
        type: string
      box:
        required: true
        type: string
jobs:
  molecule:
    name: Run Molecule tests - ${{ inputs.role_name }}
    runs-on:
      - self-hosted
      - linux
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.working_directory }}
      - name: Run Molecule tests
        working-directory: '${{ inputs.working_directory }}'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          cd ./roles/${{ inputs.role_name }}
          molecule test
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ inputs.box }}
