---
name: Generate Role Docs
'on':
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      role_name:
        required: true
        type: string
jobs:
  docs:
    name: Generate ${{ inputs.role_name }} role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.working_directory }}
          ref: main
      - name: Generate test role documentation
        working-directory: '${{ inputs.working_directory }}'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/${{ inputs.role_name }}
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update ${{ inputs.role_name }} role documentation." || /bin/true
          git push origin main
          deactivate
